<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Avalonia.Headless" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Cindara.Desktop\Cindara.Desktop.csproj" />
    <EmbeddedResource Include="..\..\src\Cindara.Desktop\Styles\Components.axaml"
                      LogicalName="Cindara.Tests.CardStyles.axaml" />
    <EmbeddedResource Include="..\..\src\Cindara.Desktop\Views\DesignGalleryView.axaml"
                      LogicalName="Cindara.Tests.DesignGallery.axaml" />
    <EmbeddedResource Include="..\..\src\Cindara.Desktop\Views\MainWindow.axaml"
                      LogicalName="Cindara.Tests.MainWindow.axaml" />
    <EmbeddedResource Include="..\..\src\Cindara.Desktop\Views\ShellView.axaml"
                      LogicalName="Cindara.Tests.ShellView.axaml" />
    <EmbeddedResource Include="..\..\src\Cindara.Desktop\Views\LibraryBrowserView.axaml"
                      LogicalName="Cindara.Tests.LibraryBrowserView.axaml" />
  </ItemGroup>
</Project>
